# Generated by Django 3.0.7 on 2020-06-22 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_caption', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=600)),
                ('heading_2', models.CharField(blank=True, max_length=200)),
                ('body_2', models.CharField(blank=True, max_length=600)),
                ('heading_3', models.CharField(blank=True, max_length=200)),
                ('body_3', models.CharField(blank=True, max_length=600)),
                ('is_published', models.BooleanField(default=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blogger.Blogger')),
            ],
        ),
    ]
