# Generated by Django 3.0.7 on 2020-06-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200623_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='quote_credit',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
