# Generated by Django 3.0.7 on 2020-06-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_quote_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='prom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='posts',
            name='prom_body',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='posts',
            name='prom_img',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
