# Generated by Django 3.0.7 on 2020-06-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200623_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='prom',
            new_name='promo',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='prom_body',
            new_name='promo_body',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='prom_img',
            new_name='promo_img',
        ),
    ]
