# Generated by Django 3.0.7 on 2020-06-22 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('about', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=50)),
                ('is_mvp', models.BooleanField(default=False)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
